# Generated by Django 5.1.6 on 2026-02-06 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookassignment",
            old_name="assignedBy",
            new_name="assigned_by",
        ),
        migrations.AddField(
            model_name="books",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="books",
            name="number_of_pages",
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name="books",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="students",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterModelTable(
            name="bookassignment",
            table="book_assignments",
        ),
        migrations.AlterModelTable(
            name="books",
            table="book_details",
        ),
    ]
