# Generated by Django 5.1.6 on 2026-02-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="students",
            name="password",
            field=models.CharField(blank=True, default="temp123", max_length=20),
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
