# Generated by Django 5.1.6 on 2026-02-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0004_students_password_delete_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="password",
            field=models.CharField(max_length=20),
        ),
    ]
