# Generated by Django 5.1.6 on 2026-02-06 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0005_alter_students_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="students",
            name="password",
        ),
    ]
